# Generated by Django 4.0 on 2022-01-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Контроль',
                'verbose_name_plural': 'Контроль',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('Hign', 'High')], default='Normal', max_length=6, unique=True)),
            ],
            options={
                'verbose_name': 'Приоритет',
                'verbose_name_plural': 'Приоритеты',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField(blank=True)),
                ('date_time_start', models.DateTimeField(auto_now_add=True)),
                ('date_finish', models.DateField(blank=True, null=True)),
                ('time_finish', models.TimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('reminder', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PE', 'Выполняется'), ('CO', 'Выполнено')], default='PE', max_length=11)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.priority')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField(blank=True)),
                ('date_time_start', models.DateTimeField(auto_now_add=True)),
                ('date_finish', models.DateField(blank=True, null=True)),
                ('time_finish', models.TimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('reminder', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.control')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.priority')),
            ],
            options={
                'verbose_name': 'Подзадача',
                'verbose_name_plural': 'Подзадачи',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AddField(
            model_name='control',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task'),
        ),
        migrations.AddField(
            model_name='control',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
