# Generated by Django 4.0.1 on 2022-01-12 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_subtask_control_subtask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='priority',
            field=models.ForeignKey(default='Normal', on_delete=django.db.models.deletion.CASCADE, to='app.priority'),
        ),
    ]
